// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLfUFstNZKe75eGC1WkLCOeon8HOGMGbs',
    appId: '1:246251470918:web:a1d5301c6a29fd4ff8ca47',
    messagingSenderId: '246251470918',
    projectId: 'coffee-delicia-2bb22',
    authDomain: 'coffee-delicia-2bb22.firebaseapp.com',
    storageBucket: 'coffee-delicia-2bb22.firebasestorage.app',
    measurementId: 'G-M9YTKSLMV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs93O2PSiVp_1U6daLY09DWOi09OB72yA',
    appId: '1:246251470918:android:0f2151b50fe09865f8ca47',
    messagingSenderId: '246251470918',
    projectId: 'coffee-delicia-2bb22',
    storageBucket: 'coffee-delicia-2bb22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYJcOWkwBiszFMmcJACWfQNWhBYYY4mU',
    appId: '1:246251470918:ios:790528f9b5ab3a31f8ca47',
    messagingSenderId: '246251470918',
    projectId: 'coffee-delicia-2bb22',
    storageBucket: 'coffee-delicia-2bb22.firebasestorage.app',
    iosBundleId: 'com.example.cafedelicia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkYJcOWkwBiszFMmcJACWfQNWhBYYY4mU',
    appId: '1:246251470918:ios:790528f9b5ab3a31f8ca47',
    messagingSenderId: '246251470918',
    projectId: 'coffee-delicia-2bb22',
    storageBucket: 'coffee-delicia-2bb22.firebasestorage.app',
    iosBundleId: 'com.example.cafedelicia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLfUFstNZKe75eGC1WkLCOeon8HOGMGbs',
    appId: '1:246251470918:web:e0f16016b60dc6c6f8ca47',
    messagingSenderId: '246251470918',
    projectId: 'coffee-delicia-2bb22',
    authDomain: 'coffee-delicia-2bb22.firebaseapp.com',
    storageBucket: 'coffee-delicia-2bb22.firebasestorage.app',
    measurementId: 'G-FVTZ6LLJZJ',
  );

}